# -*- coding: utf-8 -*-

es = {
        u'узыка': 'Música',
        u'ознавательные': 'Educativo',
        u'ротика': 'Adultos',
        u'ильмы': 'Películas',
        u'порт': 'Deportes',

        'SOCCER': 'Fútbol',
        'BASKETBALL': 'Baloncesto',
        'FORMULA 1': 'Formula 1',
        'MOTOGP': 'Moto GP',
        'TENNIS': 'Tenis',
        'MMA': 'Lucha',
        'CYCLING': 'Ciclismo',
        'FOOTBALL': 'Football americano',
        'BASEBALL': 'Beisbol',
        'VOLLEYBALL': 'Voleybol',
        'GOLF': 'Golf',
        'HOCKEY': 'Hockey',
        'RUGBY': 'Rugby',
        'BOXING': 'Boxeo',

        'UEFA CHAMPIONS LEAGUE': 'UEFA Champions League',
        'UEFA EUROPA LEAGUE': 'UEFA Europa League',
        'URUGUAY LEAGUE': 'Liga Uruguaya',
        'URUGUAY PRIMERA': 'Liga Uruguaya',
        'COPA SUDAMERICANA': 'Copa Sudamericana',
        'COPA LIBERTADORES': 'Copa Libertadores',
        'COLOMBIA PRIMERA': 'Liga Colombiana',
        'COLOMBIA COPA': 'Copa de Colombia',
        'ARGENTINA PRIMERA': 'Liga Argentina',
        'MEXICO COPA MX': 'Copa de Mexico',
        'MEXICO LIGA MX': 'Liga Mexicana',
        'SPANISH LA LIGA': 'La Liga',
        'SPANISH LA LIGA 2': 'La Liga 123',
        'EUROLEAGUE': 'Euroliga',
        'PORTUGAL A LIGA': 'Liga Portuguesa',
        'CHILE LEAGUE': 'Liga Chilena',
        'DAVIS CUP': 'Davis CUP',
        'FRENCH LIGUE 1': 'Liga Francesa',
        'ITALY SERIE A': 'Liga Italiana',
        'PREMIER LEAGUE': 'Liga Inglesa',
        'BUNDESLIGA': 'Liga Alemana',
        'USA MLS': 'Liga de USA',
        'SPANISH ACB': 'Liga ACB',
        'USA NBA': 'NBA',
        'WBO WORLD TITLE': 'Título Mundial WBO',
        'ATP WORLD TOUR': 'ATP World Tour',
        'Spanish Primera Division': 'La Liga',
        'Spanish Segunda Division': 'La Liga 123',
        'English Premier League': 'Liga Inglesa',
        'French Ligue 1': 'Liga Francesa',
        'Italian Serie A': 'Liga Italiana',
        'German Bundesliga': 'Liga Alemana'
    }
